# Generated by Django 6.0.2 on 2026-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_remove_document_content_remove_document_e_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
