# Generated by Django 6.0.2 on 2026-02-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_department_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
