# Generated by Django 6.0.2 on 2026-02-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('head', 'Department Head'), ('executive', 'Executive'), ('governor', 'Governor')], default='employee', max_length=20),
        ),
    ]
